### ISSUE TITLE
JSON Request fromat

### ISSUE THREAD

**Issue by Nikhil20051523** [Nikhil1479/fastapi#6]
Please include the `JSON` request and response format.

**Comment by Nikhil1479** [comment]
Sure will add soon.

**Comment by Nikhil1479** [comment]
### Request Body
```json
{
    "title": "My vacation to miami",
    "content": "checkout some awesome photos",
    "rating": 5
    }
```

### Response Structure
```json
{
    "data": {
        "title": "My vacation to miami",
        "content": "checkout some awesome photos",
        "published": true,
        "rating": 5,
        "type": "Response",
        "id": 229597
    }
}
```

**Comment by Nikhil20051523** [comment]
> ### Request Body
> ```json
> {
>     "title": "My vacation to miami",
>     "content": "checkout some awesome photos",
>     "rating": 5
>     }
> ```
> 
> ### Response Structure
> ```json
> {
>     "data": {
>         "title": "My vacation to miami",
>         "content": "checkout some awesome photos",
>         "published": true,
>         "rating": 5,
>         "type": "Response",
>         "id": 229597
>     }
> }
> ```

Thanks, it works
